version: '3'
services:
  test-runner:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pytest --alluredir=allure-results --cov=. &&
             allure generate allure-results -o reports/allure-report --clean"
